### ISSUE TITLE
1.18.2 All time when pantalassa vehicles trying to load i got a crash.

### ISSUE THREAD

**Issue by i218** [Sniffity/Panthalassa#13]
[crash-2022-10-19_19.33.46-client.txt](https://github.com/Sniffity/Panthalassa/files/9822497/crash-2022-10-19_19.33.46-client.txt)
When i plase new vehicles or turn my head at already existing vehicles direction i got this (file).

Please add comand to destroy vehicles in current chunk (or radius of chunks) + config to disable their spawn at labs.
Also, when i trying to enter world created with pantalassa without pantalassa mod i got "world couldn't be launched due to texture pack error" please make pantalassa things dissapear if mod deleted.

**Comment by Sniffity** [comment]
Issue is fixed in my dev environment - should release an update soon!

**Comment by i218** [comment]
Ty.
For fix, and for reply.
