### ISSUE TITLE
Problem with rendering a vehichle

### ISSUE THREAD

**Issue by iabusemydog** [Sniffity/Panthalassa#17]
Watching my friend play on a server with this amazing mod but anytime he or my other 2 friends gets near the laboratory he crashes and gets this code com.github.sniffity.panthalassa.client.render.PanthalassaVehicleRenderer.getRenderColor(Ljava/lang/Object;FLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;Lcom/mojang/blaze3d/vertex/IVertexBuilder;I)Ljava/awt/Color;

**Comment by ramensen** [comment]
Yeah i have the same issue, i dont know whats going on

**Comment by Kori321** [comment]
Same problem.
[crash p.txt](https://github.com/Sniffity/Panthalassa/files/11225269/crash.p.txt)

**Comment by Matveyee** [comment]
Hey guys. Do you have solution now? It would be really nice((

**Comment by Sniffity** [comment]
Fixed for latest 1.16.5 release.
