### ISSUE TITLE
[1.18.1] Mobs sometimes get stuck in shallow water/near blocks

### ISSUE THREAD

**Issue by Raidobw2** [Sniffity/Panthalassa#8]
## Description
Hello, mobs sometimes get stuck in shallow water or near blocks. Once they are aggro'ed towards the player in survival, they get stuck when there is little amount of water. This happens with all mobs that can attack the player (e.g. those that are passive at first). When switching to creative, some of the mobs are able to move freely again, but others still remain stuck. In survival especially, if you are initially on an island and go swim, they will not follow you, despite being aggro'ed to you.
Thank you and good luck with development! :)

## Versions
Minecraft: 1.18.1
Forge: 39.0.76
Panthalassa: panthalassa-1.0.1-1.18.1.jar

## Screenshots
![image](https://user-images.githubusercontent.com/17010632/153798009-e0efe456-3b69-4777-95df-e5bdcac40940.png)
![image](https://user-images.githubusercontent.com/17010632/153798060-925c792b-25a9-4eb3-b4da-214f7b92799f.png)
![image](https://user-images.githubusercontent.com/17010632/153798082-3b4cfd73-99c9-46c7-84b3-285aed3a9451.png)
![image](https://user-images.githubusercontent.com/17010632/153798113-733e4069-de1e-4846-865a-05a60fd9e464.png)
![image](https://user-images.githubusercontent.com/17010632/153798200-b11dc449-d851-41a8-b49e-d0ba62874e04.png)
![image](https://user-images.githubusercontent.com/17010632/153798964-e1c712ad-ecb4-441d-86db-2347e7ef874d.png)

**Comment by Sniffity** [comment]
Thank you for reporting this.

I've noticed it on occasion on testing, this description of the issue does help narrow this down quite a bit!

I believe this mostly has to do with mobs not stopping their attempts to pathfind towards a target when the target is on land. I'll attempt to improve this AI in the next update.

Thank you once again for the detailed report!

**Comment by Sniffity** [comment]
Looks to be fixed in-dev!

**Comment by Raidobw2** [comment]
Thank you 😄
